### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by Lizena2314** [notrogan/NoFox#1]
I tried all versions all possible scenarios but still dont work. Please fix it i really need this plugin. :((

Idk how it works but i add plugin to my plugins folder and then load my save. THE FUCKING KIDNAPPER FOX AND HIS FUCKING SHROUDS STILL STANDING THERE.

**Comment by notrogan** [comment]
Hello!

As far as I am aware the current version (`1.1.3`) will only apply to new save files. However, if you do need to retroactively apply the mod to past saves then I believe the version you're looking for is `1.0.3`. 

Note that version `1.0.3` is obsolete as it is `Client Sided` as opposed to `1.1.3` which is `Server Sided`, and you will not receive any support regarding this version.

That being said, can you provide a `BepInEx` log file so I can take a look at it?
